# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.FloatField(choices=[(29.99, 'Standard'), (39.99, 'Premium'), (29.99, 'Standard [PARENTAL BOOKING]'), (39.99, 'Premium [PARENTAL BOOKING]')])),
                ('booking_hours', models.FloatField()),
                ('booking_mua', models.BooleanField(default=False, verbose_name='MUA')),
                ('booking_stylist', models.BooleanField(default=False, verbose_name='Stylist')),
                ('booking_sunbed', models.BooleanField(default=False, verbose_name='sunbed')),
                ('first_name', models.CharField(default='firstname', max_length=30)),
                ('last_name', models.CharField(default='lastname', max_length=30)),
                ('your_age', models.IntegerField()),
                ('childs_age', models.IntegerField()),
                ('booking_comments', models.TextField(max_length=100)),
                ('fee', models.FloatField()),
                ('child_first_name', models.CharField(default='note: only required when booking for a person under 18.', max_length=80)),
                ('child_last_name', models.CharField(default='note: only required when booking for a person under 18.', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('address', models.TextField(default='i have no home lol', max_length=200)),
                ('age', models.TextField(max_length=10)),
                ('telephone', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PageBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.TextField(max_length=10)),
                ('title', models.TextField(max_length=50)),
                ('info', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesBluePrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField(max_length=30)),
                ('service_desc', models.TextField(max_length=250)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
