# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_site', '0002_auto_20170805_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='your_age',
            field=models.IntegerField(null=True),
        ),
    ]
