# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_site', '0006_auto_20170805_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time_submission',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
